FROM python:3.12-slim

# Install uv
RUN pip install uv

WORKDIR /app

# Copy the dependency file and install dependencies
COPY pyproject.toml .
RUN uv pip install --system .[dev]

COPY . .

CMD ["uvicorn", "todo_app.main:app", "--host", "0.0.0.0", "--port", "8001"]
